# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1be1f251845ca6fc75fdfdbfbaa33eacbf9415f06a97a52b8f249763ca3b7c0a10dec30ded18c1011d129d3b7189ad7f99261186aec0fbe3fdd28b7516440fcd

test:
  secret_key_base: 0c7f55d7ffab0920d6ac4e0f8350d2f15334e5295a6b502069b8e468505d6755af4a611fb29fe2d704b59ed5d32fd6330407400f674d7d5a9b0ef8b7e4189f46

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
